### ISSUE TITLE
git lfs clone시 batch response

### ISSUE THREAD

**Issue by E-nan** [francis-kang/handson-unsupervised-learning#2]
```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/francis-kang/handson-unsupervised-learning.git/info/lfs'
```
glt lfs clone 을 하면 위와 같이 뜨면서 csv파일들이 제대로 클론이 되지 않습니다. pull 받으려면 제가 LFS 데이터팩을 구매해야 하는건가요??

**Comment by E-nan** [comment]
README.md 파일에 작성해주신 캐글 링크도 404가 뜨는 상태입니다. 예제 데이터를 어디서 구할 수 있을까요 ㅠㅠ

**Comment by francis-kang** [comment]
안녕하세요.
메일 확인이 늦어서 죄송합니다.
git lfs 무료 버전이 다운로드/업로드 양이 제한 (스토리지 1G, 대역폭 1G)되어있어서 발생한 에러 같습니다. 한달이 지나면
갱신되는데요.. (저도 갱신되는 시점을 알지는 못합니다.. ㅠ)

지금 당장 다운로드 받으시려면,
기존의 git lfs pull 명령어가 실패해도 사이즈가 가장 큰 credit_card.csv 파일(144MB)만 제외하고는 다운로드가
되기 때문에 다음의 경*로(*https://www.kaggle.com/mlg-ulb/creditcardfraud) 에서
*credit_card.csv
파일만 직접 다운로드 하시면 됩니다. *

데이터 관련 다운로드와 관련해서는 git 웹 readme 파일의 "실습 데이터 셋 다운로드 경로 및 참고 사항"을 참조하시면 좋을 것
같습니다.

마지막으로 불편을끼쳐 드려서 죄송하구요.. ㅠ
무료 버전에서 제공하는 업/다운 양정도로도 괜찮을거라고 생각했는데 최근 관련 에러 문의가 많으시더라구요,.
조만간 유료로 전환하는 큰 용기를 내어볼까 합니다..


감사합니다.
강재원 드림

2021년 1월 28일 (목) 오전 10:07, Enan <notifications@github.com>님이 작성:

**Comment by E-nan** [comment]
답변해주셔서 감사합니다. ㅎㅎ
캐글에 credit card fraud 라고 검색하니 나오는군요. 좀 더 찾아볼걸 그랬습니다.

저와 같은 문제를 겪으신 분들은 강재원님께서 답해주신 답변처럼 해당 경로로 접속해 파일을 다운로드 받거나,
캐글( https://www.kaggle.com )에 접속하셔서 credit card fraud 라고 검색하시면 데이터 파일을 다운로드 받으실 수 있습니다.
